### ISSUE TITLE
add NSM support

### ISSUE THREAD

**Issue by Houston4444** [SpotlightKid/qjackcapture#1]
I think that a NSM support would be interesting for this tool.
The main idea is that records would go into a folder inside the session.
It could also offer show/hide GUI option, and save settings per session too.

**Comment by SpotlightKid** [comment]
Yes, I thought about that too already. I wouldn't like adding `pyliblo` as a dependency, though. Is there a Qt-based OSC library (for Python)?

Or I could just add https://github.com/jackaudio/new-session-manager/blob/master/extras/pynsm/nsmclient.py, I guess.

**Comment by Houston4444** [comment]
> Yes, I thought about that too already.

cool.

> Is there a Qt-based OSC library (for Python)?

I would be very surprised to see that a such thing exists. I use my own stuff with Qt and liblo to manage Ray internal NSM clients, but I am going to change this because Qt use is overrated in these cases (ray-jackpatch should not use Qt at all). However, pyqtSignals are convenient for this usage.

> Or I could just add https://github.com/jackaudio/new-session-manager/blob/master/extras/pynsm/nsmclient.py, I guess.

Yes, this is the simplest way I think.

**Comment by SpotlightKid** [comment]
I have a first implementation of NSM support ready in #4.

I decided to *not* set the output folder for audio files to the NSM session folder, since these files are not meant to be loaded again by QJacKCapture and are not part of the session. They are exports. The output folder path and the audio output filename prefix are of course saved in the session settings, as are all the other settings. `optional-gui` is also fully implemented.

If you have time, please test. I've attached a source archive built from the `feat/nsm-support` branch to #4.

**Comment by Houston4444** [comment]
> I decided to not set the output folder for audio files to the NSM session folder, since these files are not meant to be loaded again by QJacKCapture and are not part of the session. They are exports.

I think there is not only one right way to see the thing. I understand the idea that the session doesn't depends on exports. What I would like is a program I launch, don't care any setting, record, and then I know I will find the record files very easily, and the session dir is a good place for this.
Now lets consider the case where we archive/copy the session for someone else or another machine, of course exports are not needed, but in musical work, this is probably the first thing the other one will listen.
On the other hand, having a directory where we find all exports from several sessions can be convenient. A way to satisfied all theses views would be to add symlink of each export file in the session folder (in the path given by the server for the client).  This could be optional of course.

**Comment by SpotlightKid** [comment]
> A way to satisfied all theses views would be to add symlink of each export file in the session folder

I added issue #7 to track this.
