### ISSUE TITLE
SIGINT/SIGTERM support

### ISSUE THREAD

**Issue by Houston4444** [SpotlightKid/qjackcapture#10]
launched under NSM, no problem. But when launched directly, Ctrl+C in the terminal never returns and freeze the window.

**Comment by SpotlightKid** [comment]
Yeah, this is a known problem with PyQt. For signal handlers attached via Python to work, the Python interpreter needs the opportunity from time to time to check the signals. If the program spends all it's time in a C/C++-level function (e.g. `app.exec_()`), that doesn't happen.

A workaround is to attach a Python function to a `QTimer` and run that periodically. The NSM-mode did that already to call into the `NSMClient` class to handle OSC messages. I've now attached a no-op function to a `QTimer` in non-NSM mode as well and added handlers for `SIGINT` and `SIGTERM`.
