### ISSUE TITLE
The Filetype combobox is empty

### ISSUE THREAD

**Issue by yurivict** [SpotlightKid/qjackcapture#3]
... and it wrote the file without extension: ```jack_capture_01.```.

**Comment by SpotlightKid** [comment]
Curious. Can you copy and paste the output of `jack_cpture -pf` here?

Is the output from `LC_ALL=C jack_capture -pf` any different?

**Comment by yurivict** [comment]
They both return empty output.

**Comment by SpotlightKid** [comment]
I think that means that, unfortunately, the version of jack_capture you have installed is not compatible with QJackCapture. How did you install it? Which version is it?

**Comment by yurivict** [comment]
jack-capture is installed from the latest revision of https://github.com/kmatheussen/jack_capture 

Is this a wrong project?

**Comment by SpotlightKid** [comment]
No, it's the correct one, but make sure you compile it with libsndfile support.

**Comment by yurivict** [comment]
It is compiled with libsndfile support.

**Comment by SpotlightKid** [comment]
Then I don't understand why `jack_capure -pf` outputs nothing.

Just to double-check, at compilation, do you get this output?

```
jack_capture was configured with the following options:
------------------------------
#define HAVE_OGG 1
#define HAVE_LAME 1
//COMPILEFLAGS -lmp3lame
#define HAVE_LIBLO 1
//COMPILEFLAGS  -llo
#define NEW_JACK_LATENCY_API 1
------------------------------
```

And does `ldd /usr/bin/jack_capture` (or the equivalent under BSD) show that libsndfile is linked?

	linux-vdso.so.1 (0x00007fffcd5af000)
	libjack.so.0 => /usr/lib/libjack.so.0 (0x00007fcab564f000)
	libsndfile.so.1 => /usr/lib/libsndfile.so.1 (0x00007fcab55ce000)
	libm.so.6 => /usr/lib/libm.so.6 (0x00007fcab54e6000)
	libmp3lame.so.0 => /usr/lib/libmp3lame.so.0 (0x00007fcab546e000)
	liblo.so.7 => /usr/lib/liblo.so.7 (0x00007fcab545a000)
	libc.so.6 => /usr/lib/libc.so.6 (0x00007fcab5273000)
	libdb-5.3.so => /usr/lib/libdb-5.3.so (0x00007fcab50b2000)
	libstdc++.so.6 => /usr/lib/libstdc++.so.6 (0x00007fcab4e00000)
	libgcc_s.so.1 => /usr/lib/libgcc_s.so.1 (0x00007fcab5092000)
	libvorbisenc.so.2 => /usr/lib/libvorbisenc.so.2 (0x00007fcab4d55000)
	libFLAC.so.12 => /usr/lib/libFLAC.so.12 (0x00007fcab504f000)
	libopus.so.0 => /usr/lib/libopus.so.0 (0x00007fcab4cfb000)
	libvorbis.so.0 => /usr/lib/libvorbis.so.0 (0x00007fcab4ccd000)
	libogg.so.0 => /usr/lib/libogg.so.0 (0x00007fcab5042000)
	/lib64/ld-linux-x86-64.so.2 => /usr/lib64/ld-linux-x86-64.so.2 (0x00007fcab56fe000)
	libpthread.so.0 => /usr/lib/libpthread.so.0 (0x00007fcab503d000)

**Comment by SpotlightKid** [comment]
Also, what does `sndfile-convert -h` report?

**Comment by yurivict** [comment]
The configure prints the same.
jack_capture is linked with the same libraries,
```sndfile-convert -h```  prints many supported formats.

And ```jack_capture -pf``` prints nothing.

**Comment by SpotlightKid** [comment]
Then this should be reported as an issue here: https://github.com/kmatheussen/jack_capture/issues

If you could open an issue and post the contents of the `setformat.c` file, which is generated during the build of `jack_capture`, that would be great.

What happens, if you, for example, run `jack_capture -f flac`? Does `jack_capture` write a FLAC output file? What is it's output?

**Comment by yurivict** [comment]
Poor coding practice [here](https://github.com/kmatheussen/jack_capture/blob/master/gen_setformat_c.sh#L66) caused the error.

Quiz: find 3 errors in one line. -)

**Comment by SpotlightKid** [comment]
A proper solution could be based on https://github.com/libsndfile/libsndfile/blob/master/examples/list_formats.c
