### ISSUE TITLE
Link or copy output audio files into NSM session dir

### ISSUE THREAD

**Issue by SpotlightKid** [SpotlightKid/qjackcapture#7]
From https://github.com/SpotlightKid/qjackcapture/issues/1#issuecomment-1306937388:

> I understand the idea that the session doesn't depends on exports. What I would like is a program I launch, don't care any setting, record, and then I know I will find the record files very easily, and the session dir is a good place for this.
> Now lets consider the case where we archive/copy the session for someone else or another machine, of course exports are not needed, but in musical work, this is probably the first thing the other one will listen.
> On the other hand, having a directory where we find all exports from several sessions can be convenient. A way to satisfied all theses views would be to add symlink of each export file in the session folder (in the path given by the server for the client). This could be optional of course.

I'm not sure that's possible, because QJackCapture has no direct control over the final filename, it only provides the prefix and `jack_capture` adds a numbered suffix and the filename extension. There is no sure way to know this beforehand (also `jack-capture` might rotate the filenames during recording).

There is a way to run a script when `jack_capture` finishes writing to a file, which could then create the symlink. But I'm not sure how reliably that would work, if QJackCapture is terminated during recording.

**Comment by Houston4444** [comment]
Indeed, it seems to be complex to link files once jack_capture has done the work if we can't be sure of the file name and even number of files.

Would you accept a PR for having optionally the files recorded in a dir in the session ? That means I would add a checkbox (hidden if not under NSM), probably at the right of the output folder line. If checked it would set the lineedit read only and disable the browse button, it could also write the output dir in the lineedit (read only). The dir containing the audio files should be simply the path given by NSM server to this client.

Personally, I would prefer a such behavior, even if your choice to export outside the session is perfectly understandable.

**Comment by SpotlightKid** [comment]
I have a different suggestion: have look at #5. I plan to implement a similar bevahiour for the Output folder field. Then under NSM the default would be ${sessiondir}.

**Comment by Houston4444** [comment]
Just tested. Yes, very good idea.

> Then under NSM the default would be ${sessiondir}.

If {sessiondir} is the dirname of the path given by server, I would say ${sessiondir}/records for default (and for example).

**Comment by SpotlightKid** [comment]
> I plan to implement a similar bevahiour for the Output folder field.

This is now implemented in #13. Feel free to test it. Please note that the path of the QJackCapture INI-file within the NSM session dir has changed.

**Comment by Houston4444** [comment]
> the path of the QJackCapture INI-file within the NSM session dir has changed.

it is a wise choice.

Nice.

This is cool. I find the {sessiondir} template name quite confusing, it makes me think to the NSM session dir (its parent directory). Maybe {nsmclientdir} would be more appropriate.

Something else, really not strong but easily fixable. At first record, a dialog asks user if we should create the directory. Maybe, if under NSM, and if output folder combobox has not been changed, lets create this directory without dialog ask.

**Comment by SpotlightKid** [comment]
> Maybe {nsmclientdir} would be more appropriate.

I have changed some of the placeholder names, so that all NSM related ones now start with "nsm" and `${sessiondir}` became `${nsmclientdir}` as you suggested.

**Comment by SpotlightKid** [comment]
Closing in favour of #13.
